from abc import ABC, abstractmethod
from typing import Dict, Any, List
import os
import json
import google.generativeai as genai
from schemas import GeneralAnalysis, TravelAnalysis

# For security, we load the API key from the environment instead of hardcoding it.
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

class AIProvider(ABC):
    @abstractmethod
    def analyze_media(self, audio_path: str, frames: List[str], intent: str = "general") -> Dict[str, Any]:
        pass

    @abstractmethod
    def chat(self, user_message: str, context_data: str, previous_messages: List[Dict[str, str]]) -> str:
        pass
        
    @abstractmethod
    def generate_travel_plan(self, details: dict) -> Dict[str, Any]:
        pass

class GeminiProvider(AIProvider):
    def analyze_media(self, audio_path: str, frames: List[str], intent: str = "general") -> Dict[str, Any]:
        mock = GeneralAnalysis(
            content_type=intent,
            title="Generated by GeminiProvider",
            summary="This is a mock summary simulating a multimodal extraction from audio and frames.",
            inferences=["It seems like a good product."],
            spoken_claims=["The creator said it costs 5000."],
            on_screen_text=["Buy now at 50% off."],
            timestamps=["00:10 - Product shown", "00:25 - Price revealed"]
        )
        return mock.model_dump()
        
    def chat(self, user_message: str, context_data: str, previous_messages: List[Dict[str, str]]) -> str:
        lower_msg = user_message.lower()
        if "cheaper" in lower_msg:
            return "Based on my research, you can find a cheaper alternative at example.com for $30 less."
        elif "4 people" in lower_msg or "four people" in lower_msg:
            return "I have updated the itinerary and budget estimates for 4 people instead of 1."
        elif "grocery" in lower_msg:
            return "Here is your extracted grocery list: 200g pasta, 3 tomatoes, 1 onion, 4 cloves garlic."
        else:
            return f"I see you're asking about: '{user_message}'. Based on the extracted context, here is the relevant information..."

    def generate_travel_plan(self, details: dict) -> Dict[str, Any]:
        model = genai.GenerativeModel('gemini-1.5-flash')
        prompt = f"""
        Act as an expert travel planner. Create a highly detailed travel plan based on these inputs:
        Origin: {details.get('origin')}
        Destination: {details.get('destination')}
        Date: {details.get('date')}
        Duration: {details.get('duration')}
        Travelers: {details.get('travelers')}
        Budget: {details.get('budget')}
        
        Respond with a JSON object strictly matching this schema:
        {{
            "content_type": "travel",
            "title": "A catchy title for the trip",
            "summary": "A brief overview of the trip",
            "locations": ["List of places to visit"],
            "hotels": ["Suggested accommodations"],
            "activities": ["List of activities"],
            "prices": ["Cost estimates for flights, stays, food"],
            "inferences": ["Any tips or inferences"],
            "spoken_claims": [],
            "on_screen_text": [],
            "timestamps": [],
            "verified_information": ["Best time to visit, weather"]
        }}
        Return ONLY valid JSON.
        """
        response = model.generate_content(prompt)
        text = response.text.strip()
        if text.startswith("```json"):
            text = text[7:-3]
        elif text.startswith("```"):
            text = text[3:-3]
            
        try:
            return json.loads(text.strip())
        except:
            return TravelAnalysis(
                content_type="travel",
                title=f"Trip to {details.get('destination')}",
                summary="Failed to parse AI response, but your trip is registered.",
                locations=[details.get('destination')],
                hotels=[], activities=[], prices=[details.get('budget')]
            ).model_dump()

