from abc import ABC, abstractmethod
from typing import Dict, Any, List
import os
import json
import google.generativeai as genai
from schemas import GeneralAnalysis

genai.configure(api_key=os.getenv("GEMINI_API_KEY", "mock-key"))

class AIProvider(ABC):
    @abstractmethod
    def analyze_media(self, audio_path: str, frames: List[str], intent: str = "general") -> Dict[str, Any]:
        """
        Analyze extracted audio and frames and return a structured JSON response.
        """
        pass

    @abstractmethod
    def chat(self, user_message: str, context_data: str, previous_messages: List[Dict[str, str]]) -> str:
        """
        Respond to a user query using the extracted context and conversation history.
        """
        pass

class GeminiProvider(AIProvider):
    def analyze_media(self, audio_path: str, frames: List[str], intent: str = "general") -> Dict[str, Any]:
        # For MVP, we will just return mock structured data.
        # In actual implementation, we upload audio_path and frames to Gemini via genai.upload_file()
        # and request the output in JSON matching one of the schemas.
        
        print(f"[GeminiProvider] Received audio: {audio_path}")
        print(f"[GeminiProvider] Received {len(frames)} frames")
        
        mock = GeneralAnalysis(
            content_type=intent,
            title="Generated by GeminiProvider",
            summary="This is a mock summary simulating a multimodal extraction from audio and frames.",
            inferences=["It seems like a good product."],
            spoken_claims=["The creator said it costs 5000."],
            on_screen_text=["Buy now at 50% off."],
            timestamps=["00:10 - Product shown", "00:25 - Price revealed"]
        )
        return mock.model_dump()
        
    def chat(self, user_message: str, context_data: str, previous_messages: List[Dict[str, str]]) -> str:
        """
        MVP chat mock. In production, this builds a prompt containing context_data
        and previous_messages, and sends it to the Gemini API.
        """
        print(f"[GeminiProvider] Chat context loaded. Previous messages count: {len(previous_messages)}")
        print(f"[GeminiProvider] User asks: {user_message}")
        
        # Mock response handling simple intents for MVP demonstration
        lower_msg = user_message.lower()
        if "cheaper" in lower_msg:
            return "Based on my research, you can find a cheaper alternative at example.com for $30 less."
        elif "4 people" in lower_msg or "four people" in lower_msg:
            return "I have updated the itinerary and budget estimates for 4 people instead of 1."
        elif "grocery" in lower_msg:
            return "Here is your extracted grocery list: 200g pasta, 3 tomatoes, 1 onion, 4 cloves garlic."
        else:
            return f"I see you're asking about: '{user_message}'. Based on the extracted context, here is the relevant information..."
