from abc import ABC, abstractmethod
from typing import Dict, Any, List
import os
import json
import google.generativeai as genai
from schemas import GeneralAnalysis, TravelAnalysis

# For security, we load the API key from the environment instead of hardcoding it.
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

class AIProvider(ABC):
    @abstractmethod
    def analyze_media(self, audio_path: str, frames: List[str], intent: str = "general") -> Dict[str, Any]:
        pass

    @abstractmethod
    def chat(self, user_message: str, context_data: str, previous_messages: List[Dict[str, str]]) -> str:
        pass
        
    @abstractmethod
    def generate_travel_plan(self, details: dict) -> Dict[str, Any]:
        pass
        
    @abstractmethod
    def shopping_chat(self, message: str, image_path: str = None) -> str:
        pass

class GeminiProvider(AIProvider):
    def analyze_media(self, audio_path: str, frames: List[str], intent: str = "general") -> Dict[str, Any]:
        mock = GeneralAnalysis(
            content_type=intent,
            title="Generated by GeminiProvider",
            summary="This is a mock summary simulating a multimodal extraction from audio and frames.",
            inferences=["It seems like a good product."],
            spoken_claims=["The creator said it costs 5000."],
            on_screen_text=["Buy now at 50% off."],
            timestamps=["00:10 - Product shown", "00:25 - Price revealed"]
        )
        return mock.model_dump()
        
    def chat(self, user_message: str, context_data: str, previous_messages: List[Dict[str, str]]) -> str:
        lower_msg = user_message.lower()
        if "cheaper" in lower_msg:
            return "Based on my research, you can find a cheaper alternative at example.com for $30 less."
        elif "4 people" in lower_msg or "four people" in lower_msg:
            return "I have updated the itinerary and budget estimates for 4 people instead of 1."
        elif "grocery" in lower_msg:
            return "Here is your extracted grocery list: 200g pasta, 3 tomatoes, 1 onion, 4 cloves garlic."
        else:
            return f"I see you're asking about: '{user_message}'. Based on the extracted context, here is the relevant information..."

    def generate_travel_plan(self, details: dict) -> Dict[str, Any]:
        model = genai.GenerativeModel('gemini-1.5-flash')
        prompt = f"""
        Act as an expert travel planner. Create a highly detailed travel plan based on these inputs:
        Origin: {details.get('origin')}
        Destination: {details.get('destination')}
        Date: {details.get('date')}
        Duration: {details.get('duration')}
        Travelers: {details.get('travelers')}
        Budget: {details.get('budget')}
        
        Respond with a JSON object strictly matching this schema:
        {{
            "content_type": "travel",
            "title": "A catchy title for the trip",
            "summary": "A brief overview of the trip",
            "locations": ["List of places to visit"],
            "hotels": ["Suggested accommodations"],
            "activities": ["List of activities"],
            "prices": ["Cost estimates for flights, stays, food"],
            "inferences": ["Any tips or inferences"],
            "spoken_claims": [],
            "on_screen_text": [],
            "timestamps": [],
            "verified_information": ["Best time to visit, weather"]
        }}
        Return ONLY valid JSON.
        """
        response = model.generate_content(prompt)
        text = response.text.strip()
        if text.startswith("```json"):
            text = text[7:-3]
        elif text.startswith("```"):
            text = text[3:-3]
            
        try:
            return json.loads(text.strip())
        except:
            return TravelAnalysis(
                content_type="travel",
                title=f"Trip to {details.get('destination')}",
                summary="Failed to parse AI response, but your trip is registered.",
                locations=[details.get('destination')],
                hotels=[], activities=[], prices=[details.get('budget')]
            ).model_dump()

    def shopping_chat(self, message: str, image_path: str = None) -> str:
        model = genai.GenerativeModel('gemini-1.5-flash')
        
        prompt = "You are Sarthak, an expert AI personal shopper. Help the user find the best product at the best price online. Provide real links or estimated prices based on your knowledge. If they provided an image, describe what you see and find that exact item. "
        prompt += f"User message: {message}"
        
        contents = [prompt]
        
        if image_path:
            try:
                uploaded_img = genai.upload_file(path=image_path)
                contents.append(uploaded_img)
            except Exception as e:
                print(f"Error uploading image to Gemini: {e}")
                
        try:
            response = model.generate_content(contents)
            return response.text
        except Exception as e:
            return f"I had some trouble searching for that right now. Error: {str(e)}"

    def recipe_chat(self, message: str) -> str:
        model = genai.GenerativeModel('gemini-1.5-flash')
        
        prompt = "You are a master chef. Provide a step-by-step recipe in note format, just like a cook. Include ingredients with exact measurements, preparation steps, and cooking instructions. Be warm and encouraging. "
        prompt += f"\nUser asks to cook: {message}"
        
        try:
            response = model.generate_content(prompt)
            return response.text
        except Exception as e:
            return f"My kitchen is a bit messy right now, I couldn't get that recipe. Error: {str(e)}"
